In [1]:
import pandas as pd
import numpy as np

import statsmodels.api as sm

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

Description of data: 
    
- **Pregnancies**: Number of times pregnant
    
- **Glucose**: Plasma glucose concentration over 2 hours in an oral glucose tolerance test
    
- **BloodPressure**: Diastolic blood pressure (mm Hg)
    
- **SkinThickness**: Triceps skin fold thickness (mm)
    
- **Insulin**: 2-Hour serum insulin (mu U/ml)
        
- **BMI**: Body mass index (weight in kg/(height in m)2)
    
- **DiabetesPedigreeFunction**: Diabetes pedigree function (a function which scores likelihood of diabetes based on family history)
    
- **Age**: Age (years)
    
- **Outcome**: Class variable (0 if non-diabetic, 1 if diabetic)

In [4]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [5]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

We will like to estimate the following model:

$y=\beta_1 + \beta_1(Glucose) + \beta_2(BMI) + \beta_3(Age) + \epsilon$

In [6]:
# Setting dependent and independent variables 
# Remember to add constant term to your X

Y = df['Outcome']
X = df[['Glucose', 'BMI', 'Age']]
X = sm.add_constant(X)

In [7]:
# Linear Probablity Model 


smols = sm.OLS(Y, X)

results = smols.fit()

print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                Outcome   R-squared:                       0.271
Model:                            OLS   Adj. R-squared:                  0.268
Method:                 Least Squares   F-statistic:                     94.62
Date:                Mon, 30 Mar 2020   Prob (F-statistic):           4.43e-52
Time:                        14:41:48   Log-Likelihood:                -399.34
No. Observations:                 768   AIC:                             806.7
Df Residuals:                     764   BIC:                             825.3
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.9157      0.081    -11.326      0.0

In [8]:
# Logit Model 


smlogit = sm.Logit(Y, X) 

results = smlogit.fit()

print(results.summary())

Optimization terminated successfully.
         Current function value: 0.491982
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:                Outcome   No. Observations:                  768
Model:                          Logit   Df Residuals:                      764
Method:                           MLE   Df Model:                            3
Date:                Mon, 30 Mar 2020   Pseudo R-squ.:                  0.2394
Time:                        14:41:48   Log-Likelihood:                -377.84
converged:                       True   LL-Null:                       -496.74
Covariance Type:            nonrobust   LLR p-value:                 2.847e-51
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -8.3937      0.666    -12.602      0.000      -9.699      -7.088
Glucose        0.0325      0.

Here I will introduce **sklearn** to you. 

- **sklearn** or **scikit-learn** is a very popular machine learning library in Python. 
- It features various classification, regression and clustering algorithms.
- It also provides many datasets for practice. 
- Some of the methods are extremely useful. 

In [9]:
# First import LinearRegression and LogisticRegression

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

# train_test_split is design for separating samples into training sample and testing sample
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [11]:
skols = LinearRegression().fit(X_train, Y_train) 

One issue with sklearn is that it does not provide a nice table for estimation results like statsmodel does. 

In [12]:
print(skols.coef_)
print(skols.intercept_)

[0.         0.00561152 0.0130666  0.00533863]
-0.9186542895643854


In [13]:
# So, if you want more information for estimation result, use statsmodels.

trainols = sm.OLS(Y_train, X_train)

results = trainols.fit()

print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                Outcome   R-squared:                       0.268
Model:                            OLS   Adj. R-squared:                  0.264
Method:                 Least Squares   F-statistic:                     74.44
Date:                Mon, 30 Mar 2020   Prob (F-statistic):           4.89e-41
Time:                        14:41:48   Log-Likelihood:                -324.78
No. Observations:                 614   AIC:                             657.6
Df Residuals:                     610   BIC:                             675.2
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.9187      0.091    -10.053      0.0

But we can take advantage of its predicting features. 

In [14]:
# We can have predicted probablities for testing sample. 

y_hat = skols.predict(X_test)
y_hat

array([ 0.8760452 ,  0.24360456,  0.08555131,  0.62224643,  0.1911603 ,
        0.01157747,  0.55734924,  0.78169975,  0.28941931,  0.44556764,
        0.53035207,  0.98335105,  0.35071918,  0.04735415,  0.08844807,
        0.21494418,  0.70527629, -0.09637034,  0.52426478,  0.24130943,
        0.58999796,  0.41617338,  0.08063839,  0.11871634,  0.04625811,
        0.35706967,  0.04951223,  0.67861875,  0.16462806,  0.19850338,
        0.45651413,  0.29633588,  0.1807151 ,  0.38844367,  0.16862889,
        0.67285603,  0.43851964,  0.17928309,  0.3464466 ,  0.6744881 ,
        0.32792938,  0.25643748,  0.15921385,  0.75385918,  0.86829384,
       -0.23416796,  0.12877941,  0.29967166,  0.2865234 ,  0.34897987,
        0.37266673,  0.22950419,  0.677737  ,  0.47646169,  0.24681704,
       -0.47845951,  0.07139395,  0.56737519,  0.33370261, -0.11317054,
        0.73933477,  0.52242237,  0.21764196,  0.46351877,  0.65599394,
        0.73344669,  0.666064  ,  0.28002813,  0.30806715,  0.10

In [15]:
# Use 0.5 as cut-off value 

# Here is the prediction result. 

(Y_test - (y_hat>0.5)==0).sum()/len(Y_test)

0.7857142857142857

In [16]:
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
print(logreg.coef_)
print(logreg.intercept_)

[[-0.00010768  0.03107996  0.0838676   0.03051834]]
[-8.26603643]


In [18]:
# Logit Model 


smlogit = sm.Logit(Y_train,X_train) 

results = smlogit.fit()

print(results.summary())

Optimization terminated successfully.
         Current function value: 0.500161
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:                Outcome   No. Observations:                  614
Model:                          Logit   Df Residuals:                      610
Method:                           MLE   Df Model:                            3
Date:                Mon, 30 Mar 2020   Pseudo R-squ.:                  0.2345
Time:                        14:41:48   Log-Likelihood:                -307.10
converged:                       True   LL-Null:                       -401.18
Covariance Type:            nonrobust   LLR p-value:                 1.529e-40
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -8.2668      0.732    -11.294      0.000      -9.701      -6.832
Glucose        0.0311      0.

In [19]:
# In logit model, sklearn directly provides methods for prediction outcomes. 

print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, Y_test)))

Accuracy of logistic regression classifier on test set: 0.79


In [20]:
# Let's verify the number. 

y_hat_logit = logreg.predict(X_test)
y_hat_logit

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
      dtype=int64)

In [21]:
(Y_test -  y_hat_logit ==0).sum()/len(Y_test)

0.7922077922077922