Q1

In [2]:
import numpy as np
import pandas as pd

In [14]:
a = pd.Series(np.random.randn(10))

In [15]:
a

0   -0.582338
1   -1.054127
2   -0.907447
3   -0.315833
4   -0.269426
5   -1.044460
6   -0.897846
7   -0.363493
8   -0.938175
9    0.305084
dtype: float64

In [16]:
a = np.array(a)

In [17]:
a

array([-0.58233767, -1.05412719, -0.9074468 , -0.31583265, -0.26942569,
       -1.04445982, -0.89784607, -0.36349259, -0.93817453,  0.30508389])

In [20]:
a.reshape((10,1))

array([[-0.58233767],
       [-1.05412719],
       [-0.9074468 ],
       [-0.31583265],
       [-0.26942569],
       [-1.04445982],
       [-0.89784607],
       [-0.36349259],
       [-0.93817453],
       [ 0.30508389]])

In [21]:
a.T

array([-0.58233767, -1.05412719, -0.9074468 , -0.31583265, -0.26942569,
       -1.04445982, -0.89784607, -0.36349259, -0.93817453,  0.30508389])

In [33]:
b = np.array([np.ones(10),  pd.Series(np.random.randn(10))])

In [34]:
b

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.54796555, -0.81641693, -1.645739  ,  0.40796188, -1.02832316,
         1.04677585, -1.14847444, -0.50309899,  1.8533114 , -1.74891333]])

In [35]:
b.shape

(2, 10)

In [36]:
b.T

array([[ 1.        ,  0.54796555],
       [ 1.        , -0.81641693],
       [ 1.        , -1.645739  ],
       [ 1.        ,  0.40796188],
       [ 1.        , -1.02832316],
       [ 1.        ,  1.04677585],
       [ 1.        , -1.14847444],
       [ 1.        , -0.50309899],
       [ 1.        ,  1.8533114 ],
       [ 1.        , -1.74891333]])

In [38]:
b @ b.T

array([[10.        , -3.03495116],
       [-3.03495116, 14.06044391]])

In [41]:
np.linalg.inv(b @ b.T) 

array([[0.10701019, 0.02309818],
       [0.02309818, 0.07610726]])

In [42]:
np.linalg.inv(b @ b.T) @ (b @ b.T)

array([[1.00000000e+00, 0.00000000e+00],
       [5.55111512e-17, 1.00000000e+00]])

Optimization

In [43]:
from scipy.optimize import minimize

In [46]:
def f(x):
    return (x-1)**2

In [49]:
result = minimize(f, x0 = 0)
result

      fun: 5.5507662238258444e-17
 hess_inv: array([[0.5]])
      jac: array([4.68181046e-13])
  message: 'Optimization terminated successfully.'
     nfev: 9
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([0.99999999])

In [50]:
result.x

array([0.99999999])

OLS regression in Python 

In [3]:
# OLS in Python 

# You can use Stata, or other Python OLS packages as well 

import statsmodels.api as sm


df = pd.read_stata('data1.dta')


In [4]:
# Adding constant term manually 

df['const'] = 1

reg1 = sm.OLS(endog=df['y'], exog=df[['const', 'x']])

results = reg1.fit()

print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.799
Model:                            OLS   Adj. R-squared:                  0.799
Method:                 Least Squares   F-statistic:                     1979.
Date:                Sun, 22 Mar 2020   Prob (F-statistic):          1.33e-175
Time:                        13:23:33   Log-Likelihood:                -362.72
No. Observations:                 500   AIC:                             729.4
Df Residuals:                     498   BIC:                             737.9
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0055      0.022      0.245      0.8

In [8]:
Y = df['y']
X = df['x']
X = sm.add_constant(X)
X

const         x
0      1.0 -1.121670
1      1.0  1.001219
2      1.0 -0.588864
3      1.0 -1.608103
4      1.0 -0.421478
..     ...       ...
495    1.0 -1.213828
496    1.0  0.222661
497    1.0  0.244276
498    1.0  0.318744
499    1.0 -1.609593

[500 rows x 2 columns]

In [10]:
model = sm.OLS(Y,X)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.799
Model:                            OLS   Adj. R-squared:                  0.799
Method:                 Least Squares   F-statistic:                     1979.
Date:                Sun, 22 Mar 2020   Prob (F-statistic):          1.33e-175
Time:                        13:26:36   Log-Likelihood:                -362.72
No. Observations:                 500   AIC:                             729.4
Df Residuals:                     498   BIC:                             737.9
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0055      0.022      0.245      0.807      -0.039       0.050
x              1.0105      0.023     44.486      0.000       0.966       1.055
==============================================================================
Omnibus:                        0.044   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.978   Jarque-Bera (JB):                0.120
Skew:                           0.002   Prob(JB):                        0.942
Kurtosis:                       2.924   Cond. No.                         1.09
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

IV2SLS

In [1]:
import numpy as np
from statsmodels.api import add_constant
from linearmodels.datasets import mroz

print(mroz.DESCR)

data = mroz.load()
data = data.dropna()
data = add_constant(data, has_constant='add')




T.A. Mroz (1987), "The Sensitivity of an Empirical Model of Married Women's
Hours of Work to Economic and Statistical Assumptions," Econometrica 55,
765-799.

nlf        1 if in labor force, 1975
hours      hours worked, 1975
kidslt6    # kids < 6 years
kidsge6    # kids 6-18
age        woman's age in yrs
educ       years of schooling
wage       estimated wage from earns., hours
repwage    reported wage at interview in 1976
hushrs     hours worked by husband, 1975
husage     husband's age
huseduc    husband's years of schooling
huswage    husband's hourly wage, 1975
faminc     family income, 1975
mtr        fed. marginal tax rate facing woman
motheduc   mother's years of schooling
fatheduc   father's years of schooling
unem       unem. rate in county of resid.
city       =1 if live in SMSA
exper      actual labor mkt exper
nwifeinc   (faminc - wage*hours)/1000
lwage      log(wage)
expersq    exper^2



In [6]:
from linearmodels.iv import IV2SLS

# IV2SLS(dependent, exog, endog, instruments)

res_ols = IV2SLS(np.log(data.wage), data[['const','educ']], None, None).fit(cov_type='robust')
print(res_ols)

                            OLS Estimation Summary                            
Dep. Variable:                   wage   R-squared:                      0.1179
Estimator:                        OLS   Adj. R-squared:                 0.1158
No. Observations:                 428   F-statistic:                    65.899
Date:                Mon, Mar 23 2020   P-value (F-stat)                0.0000
Time:                        20:50:26   Distribution:                  chi2(1)
Cov. Estimator:                robust                                         
                                                                              
                             Parameter Estimates                              
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const         -0.1852     0.1703    -1.0872     0.2770     -0.5191      0.1487
educ           0.1086     0.0134     8.1178     0.00

In [7]:
res_first = IV2SLS(data.educ, data[['const','fatheduc']], None, None).fit(cov_type='robust')
print(res_first)
data['educ_hat'] = data.educ - res_first.resids

                            OLS Estimation Summary                            
Dep. Variable:                   educ   R-squared:                      0.1726
Estimator:                        OLS   Adj. R-squared:                 0.1706
No. Observations:                 428   F-statistic:                    87.528
Date:                Mon, Mar 23 2020   P-value (F-stat)                0.0000
Time:                        20:50:27   Distribution:                  chi2(1)
Cov. Estimator:                robust                                         
                                                                              
                             Parameter Estimates                              
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          10.237     0.2713     37.740     0.0000      9.7054      10.769
fatheduc       0.2694     0.0288     9.3556     0.00

In [8]:
res_second = IV2SLS(np.log(data.wage), data[['const']], data.educ, data.fatheduc).fit(cov_type='robust')
print(res_second)

                          IV-2SLS Estimation Summary                          
Dep. Variable:                   wage   R-squared:                      0.0934
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0913
No. Observations:                 428   F-statistic:                    2.5656
Date:                Mon, Mar 23 2020   P-value (F-stat)                0.1092
Time:                        20:50:27   Distribution:                  chi2(1)
Cov. Estimator:                robust                                         
                                                                              
                             Parameter Estimates                              
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          0.4411     0.4643     0.9501     0.3421     -0.4689      1.3511
educ           0.0592     0.0369     1.6017     0.10

In [9]:
from linearmodels.iv import compare
res_direct = IV2SLS(np.log(data.wage), data[['const','educ_hat']], None, None).fit(cov_type='unadjusted')
print(compare({'OLS':res_ols, '2SLS':res_second, 'Direct': res_direct}))

                       Model Comparison                       
                               OLS         2SLS         Direct
--------------------------------------------------------------
Dep. Variable                 wage         wage           wage
Estimator                      OLS      IV-2SLS            OLS
No. Observations               428          428            428
Cov. Est.                   robust       robust     unadjusted
R-squared                   0.1179       0.0934         0.0060
Adj. R-squared              0.1158       0.0913         0.0037
F-statistic                 65.899       2.5656         2.5982
P-value (F-stat)         4.441e-16       0.1092         0.1070
==================     ===========   ==========   ============
const                      -0.1852       0.4411         0.4411
                         (-1.0872)     (0.9501)       (0.9465)
educ                        0.1086       0.0592               
                          (8.1178)     (1.6017)        